# Generated by Django 5.0 on 2023-12-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogDemo', '0006_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
