# Generated by Django 5.0 on 2023-12-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogDemo', '0007_category_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='no',
        ),
    ]
