# Generated by Django 5.0 on 2024-01-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogDemo', '0016_comment_downvotes_comment_replies_comment_upvotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
    ]
