# Generated by Django 5.0 on 2024-01-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogDemo', '0023_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(related_name='comments', to='BlogDemo.comment'),
        ),
    ]
