# Generated by Django 5.0 on 2024-01-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogDemo', '0024_alter_comment_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(to='BlogDemo.comment'),
        ),
    ]
