# Generated by Django 5.0 on 2023-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('contactno', models.BigIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('passwd', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('sscm', models.IntegerField()),
                ('hscm', models.IntegerField()),
            ],
        ),
    ]
