# Generated by Django 5.0 on 2023-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contactno',
            field=models.BigIntegerField(),
        ),
    ]
