# Generated by Django 5.0 on 2023-12-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbDemo', '0004_student_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passwd',
        ),
    ]
